version: "3.3"

services:
  db:
    image: postgres:12.2
    container_name: task-tracker-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "task-tracker"
      POSTGRES_USER: "taskTrackerUser"
      POSTGRES_PASSWORD: "qwerty"

  server:
    build:
      context: ./
    container_name: task-tracker-server
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task-tracker?useUnicode=true&characterEncoding=utf8&useSSL=false
    volumes:
      - ./server/:/app/
    working_dir: /app
    user: appuser
    command: mvn clean spring-boot:run
