spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/task-tracker?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: taskTrackerUser
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: taskTracker
  validation-time: 2592000000
